### PR TITLE
fix(release): add missing @changesets/changelog-github dependency

### PR DESCRIPTION
**Pull request by clockworkgr**
## Description

The Release workflow failed after #284 was merged ([run](https://github.com/gnolang/tm2-js-client/actions/runs/34821415828)):

```
🦋  error Error: Cannot find module '@changesets/changelog-github'
```

`.changeset/config.json` (added in #268) uses `@changesets/changelog-github` as the changelog generator, but the package was never added to `devDependencies` or the lockfile.

The previous Release run found no pending changesets, so it skipped `changeset version` and went straight to publishing 2.0.5. #284 merged the first changeset, which is the first time the version step, and with it the changelog generator, actually ran.

## Changes

- Add `@changesets/changelog-github` to `devDependencies` and update `pnpm-lock.yaml`.

## Verification

- `pnpm install --frozen-lockfile` passes against the updated lockfile, matching the install step in the Release workflow.
- `pnpm version:packages` now completes: it consumes the pending #284 changeset, bumps the version to 2.1.0, and writes the changelog entry with PR and commit links.
- Lint and tests pass.

## Notes

- No changeset is included, since this only changes release tooling and not the published package.
- Re-running the failed job will not help, because it checks out a commit without the dependency. Merging this PR pushes to `main`, which triggers the Release workflow again. That run will pick up the pending #284 changeset and open the "Version Packages" PR.

### CODE REVIEW

**Review by jinoosss — APPROVED** [review]
👍
